---
# For use with pre-commit.
# See usage instructions at https://pre-commit.com
repos:
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.32.0
  hooks:
  - id: yapf

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.27.1
  hooks:
    - id: yamllint
      args: [-c=./molecule/default/yamllint.yml]
