---
# For use with pre-commit.
# See usage instructions at https://pre-commit.com
repos:
- repo: https://github.com/google/yapf
  rev: v0.40.2
  hooks:
  - id: yapf

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.35.1
  hooks:
    - id: yamllint
      args: [-c=./molecule/default/yamllint.yml]
