---
#- name: Install ansible prerequisites
#  hosts: openstack
#  gather_facts: no
#  roles:
#    - role: marvel-nccr.ansible_prerequisites

- name: Set up AiiDA lab server
  hosts: all
  roles: 
    - role: geerlingguy.docker
      become: true
      tags: docker
      vars:
        docker_users: [ '{{ ansible_user }}' ]
    - role: marvel-nccr.aiidalab_server
      tags: aiidalab_server
      vars:
        # Change to "False" in order to prevent creation of new accounts
        aiidalab_server_create_users: "True"
        aiidalab_server_docker_stack: "aiida-1.0"
        aiidalab_server_uid: 1000
        #aiidalab_server_build_locally: true
